<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="8" passed="6" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-09-19T15:24:32 BST" name="Surefire suite" finished-at="2021-09-19T15:24:36 BST" duration-ms="4182">
    <groups>
    </groups>
    <test started-at="2021-09-19T15:24:32 BST" name="Surefire test" finished-at="2021-09-19T15:24:36 BST" duration-ms="4182">
      <class name="com.org.testapi.TestForSampleAPI">
        <test-method is-config="true" signature="suiteSetup()[pri:0, instance:com.org.testapi.TestForSampleAPI@5972d253]" started-at="2021-09-19T15:24:32 BST" name="suiteSetup" finished-at="2021-09-19T15:24:32 BST" duration-ms="20" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- suiteSetup -->
        <test-method signature="validateCommentsExceptionsScenarioForNonExistPostId()[pri:0, instance:com.org.testapi.TestForSampleAPI@5972d253]" started-at="2021-09-19T15:24:32 BST" name="validateCommentsExceptionsScenarioForNonExistPostId" description="To Check the Comments Endpoint by passing wrong Id " finished-at="2021-09-19T15:24:35 BST" duration-ms="2287" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateCommentsExceptionsScenarioForNonExistPostId -->
        <test-method signature="validateCommentsExceptionsScenarioForNonExistPostIdAsQueryParameter()[pri:0, instance:com.org.testapi.TestForSampleAPI@5972d253]" started-at="2021-09-19T15:24:35 BST" name="validateCommentsExceptionsScenarioForNonExistPostIdAsQueryParameter" description="To Check the Comments Endpoint by passing wrong query parameter values " finished-at="2021-09-19T15:24:35 BST" duration-ms="121" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[MisMatch HTTPS Status code >> GET /Comments?postId=1 expected [404] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: MisMatch HTTPS Status code >> GET /Comments?postId=1 expected [404] but found [200]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at com.org.testapi.TestForSampleAPI.validateCommentsExceptionsScenarioForNonExistPostIdAsQueryParameter(TestForSampleAPI.java:172)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeLazy(TestNGDirectoryTestSuite.java:123)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:90)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateCommentsExceptionsScenarioForNonExistPostIdAsQueryParameter -->
        <test-method signature="validateForMultipleComments()[pri:0, instance:com.org.testapi.TestForSampleAPI@5972d253]" started-at="2021-09-19T15:24:35 BST" name="validateForMultipleComments" description="To Check Functional behavior of /Comments Endpoint " finished-at="2021-09-19T15:24:35 BST" duration-ms="379" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateForMultipleComments -->
        <test-method signature="validateForMultipleCommentsWithQueryParameter()[pri:0, instance:com.org.testapi.TestForSampleAPI@5972d253]" started-at="2021-09-19T15:24:35 BST" name="validateForMultipleCommentsWithQueryParameter" description="To Check the Comments Endpoint by passing query parameter " finished-at="2021-09-19T15:24:35 BST" duration-ms="145" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateForMultipleCommentsWithQueryParameter -->
        <test-method signature="validateForMultiplePostsPerUserComments()[pri:0, instance:com.org.testapi.TestForSampleAPI@5972d253]" started-at="2021-09-19T15:24:35 BST" name="validateForMultiplePostsPerUserComments" description="To get Multiple posts" finished-at="2021-09-19T15:24:35 BST" duration-ms="87" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateForMultiplePostsPerUserComments -->
        <test-method signature="validateJSONPlaceHolderWorkFlow()[pri:0, instance:com.org.testapi.TestForSampleAPI@5972d253]" started-at="2021-09-19T15:24:35 BST" name="validateJSONPlaceHolderWorkFlow" description="To get the details of a user&#039;s Posts and comments" finished-at="2021-09-19T15:24:36 BST" duration-ms="860" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateJSONPlaceHolderWorkFlow -->
        <test-method signature="validateUserPostsCommentsExceptionScenarioForNonExistUserId()[pri:0, instance:com.org.testapi.TestForSampleAPI@5972d253]" started-at="2021-09-19T15:24:36 BST" name="validateUserPostsCommentsExceptionScenarioForNonExistUserId" description="To Check Exception Cases" finished-at="2021-09-19T15:24:36 BST" duration-ms="102" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[MisMatch HTTPS Status code >> GET Posts/1456/comments expected [404] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: MisMatch HTTPS Status code >> GET Posts/1456/comments expected [404] but found [200]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at com.org.testapi.TestForSampleAPI.validateUserPostsCommentsExceptionScenarioForNonExistUserId(TestForSampleAPI.java:116)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeLazy(TestNGDirectoryTestSuite.java:123)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:90)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateUserPostsCommentsExceptionScenarioForNonExistUserId -->
        <test-method signature="validateUserPostsExceptionScenarioForNonExistUser()[pri:0, instance:com.org.testapi.TestForSampleAPI@5972d253]" started-at="2021-09-19T15:24:36 BST" name="validateUserPostsExceptionScenarioForNonExistUser" description="To Check Exception Scenario of / Posts Endpoint" finished-at="2021-09-19T15:24:36 BST" duration-ms="86" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateUserPostsExceptionScenarioForNonExistUser -->
      </class> <!-- com.org.testapi.TestForSampleAPI -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
